#site_name: "From Quantum ESPRESSO to DeePMD-kit: A Workflow for Atomistic Modeling"
site_name: "Material Modelling"

repo_url: https://github.com/didarul59/QE-relax_to_DeePMD.git

theme:
  name: material
  #custom_dir: material/overrides
  features:
    - navigation.top
    - navigation.footer
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - https://fonts.googleapis.com/css2?family=Merriweather:wght@700&display=swap


nav:
  - Home: index.md
  - DFT Calculations: dft_calculation.md
  - Training Data: training_data.md
  - Model Applications: model_application.md

